### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 524: ordinal not in range(128)

### ISSUE THREAD

**Issue by matthijsotterloo** [simonschellaert/spotify2am#1]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 524: ordinal not in range(128)

**Comment by simonschellaert** [comment]
Thanks for your feedback! This issue is resolved by commit 07a02b1 and 1a6e5e3.
