### ISSUE TITLE
Missing X-Guid number

### ISSUE THREAD

**Issue by canergen** [simonschellaert/spotify2am#22]
Hi,
I don't find any X-Guid line under Charles anymore in iTunes version 12.2.1.
Anyone else having these problems?

**Comment by ghost** [comment]
Nope, never had any problems finding it yesterday - iTunes 12.2.1.6

After the iTunes login processes are finished, play an apple music track and look at Charles to see what thread lights up yellow.    

That should have the values you need..

From:  cane11
Reply-To:  simonschellaert/spotify2am
Date:  Tuesday, 21 July 2015 12:43
To:  simonschellaert/spotify2am
Subject:  [spotify2am] Missing X-Guid number (#22)

Hi,
I don't find any X-Guid line under Charles anymore in iTunes version 12.2.1.
I think instead it is defining

 action
 lease-renew
 guid
 A45E60B88B4D
 salableAdamId
 597755284
 spc

Anyone else having these problems?
