### ISSUE TITLE
Something went wrong when inserting songs

### ISSUE THREAD

**Issue by matiasmacera** [simonschellaert/spotify2am#4]
I'm getting Something went wrong while inserting 965221594 : must be bytes or read-only buffer, not bytearray after setting the cookies values and running the script

python3 insert-songs.py

Any ideas?

**Comment by matiasmacera** [comment]
I'm getting  charles data from ld-8, not ld-4. 

```
POST /WebObjects/MZDaap.woa/daap/databases/1/cloud-add HTTP/1.1
```

Host    ld-8.itunes.apple.com:443
Proxy-Connection    keep-alive
X-Apple-Store-Front 143505-28,32 ab:SIM0
Client-iTunes-Sharing-Version   3.12
Accept-Language es-es, es;q=0.75, en-us;q=0.50, en;q=0.25
Client-Cloud-DAAP-Version   1.0/iTunes-12.2.0.145
Accept-Encoding gzip
X-Apple-itre    0
Content-Length  77
Client-DAAP-Version 3.13
User-Agent  iTunes/12.2 (Macintosh; OS X 10.10.4) AppleWebKit/0600.7.12
Connection  keep-alive
Content-Type    application/x-dmap-tagged
X-Dsid  1082359395
Cookie  accs=o; as_sfa=us; ds01=A29272A178728D18DC280F3C00A4DA168BC2D1F452AC5B351C216D31F2619300FCCF64F23947B42BE51D346953899F58B0AFB0803BCD287571400E548000BD63; dssf=1; dssid2=83f02916-f54e-485c-bd8f-461829f69f1f; isPpuOptOut=1; itspod=46; mz_at0-1082359395=AwQAAAEBAAHVJgAAAABVk8g/bJI2gcw3No3JsAoVjmt28eFaXp4=; POD=us~en; pxro=1; s_fid=78A9502DF9748E7B-0D27D53B4773657A; s_invisit_n2_us=4; s_pathLength=support%3D1%2C; s_ppv=acs%253A%253Aadf%253A%253Acat%253A%253Amusic%253A%253Aapple_music_on_mac%253A%253Atp%253A%253A7110343%253A%253ASpotify%2520is%2520better%2520than%2520Music%252C%2520don%2527t%2520switch%2520over%2520until%2520following%2520problems%2520are%2520solved%253A%2520iCloud%2520library%2520bug%252C%2520artist%2Fsong%2520stations%252C%2520playlists%2520%2528constructive%2520suggestions%2521%2529%2C71%2C43%2C2116%2C400%3A1%7C500%3A1%7C600%3A1%7C700%3A1%7C800%3A1%7C900%3A1%7C1000%3A1%7C1100%3A1%7C1200%3A1%7C1300%3A1%7C1400%3A1%7C1500%3A1%7C1600%3A1%7C1700%3A1; s_vi=[CS]v1|2ABAF08805193098-40000600E006D32B[CE]; s_vnum_n2_es=0%7C1; s_vnum_n2_us=0%7C3%2C16%7C1%2C3%7C1%2C19%7C4%2C4%7C4; TrPod=8; xp_ci=3z1qTW4z1cFz4jgzBhxzNQciUfSD
X-Guid  406C8F5A7FA7

**Comment by MatthieuTnsc** [comment]
ld-4 is https so make sure SSL Proxying is enabled and working correctly

**Comment by matiasmacera** [comment]
I think it's working fine since i can get the headers details...

**Comment by leprechuan** [comment]
I solved this by updating python to version 3.4.3 and then you go to applications/Python3.4 and run Update Shell Profile.command

**Comment by matiasmacera** [comment]
Thanks! That solved my problem.

**Comment by dannymichel** [comment]
I don't know what I'm doing wrong. Mac OS X Proxy is checked. I added '*itunes.apple.com' to SSL Proxy settings, and I'm still getting id-8
